apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.projectName }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - api.digitallapi.com
      secretName: {{ .Values.projectName }}-tls
  rules:
  - host: api.digitallapi.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.projectName }}-gql
          servicePort: 80