apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectName }}-gql
  labels:
    {{- include "graphql-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4000
  selector:
    {{- include "graphql-helm.selectorLabels" . | nindent 4 }}
